# Generated by Django 5.1.2 on 2025-01-11 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='protein',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters'), ('unit', 'units')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.CreateModel(
            name='RecipeNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('calorie_colour', models.IntegerField(choices=[(0, 'white'), (1, 'green'), (2, 'amber'), (3, 'red')])),
                ('fat', models.FloatField()),
                ('fat_colour', models.IntegerField(choices=[(0, 'white'), (1, 'green'), (2, 'amber'), (3, 'red')])),
                ('saturates', models.FloatField()),
                ('saturates_colour', models.IntegerField(choices=[(0, 'white'), (1, 'green'), (2, 'amber'), (3, 'red')])),
                ('sugars', models.FloatField()),
                ('sugars_colour', models.IntegerField(choices=[(0, 'white'), (1, 'green'), (2, 'amber'), (3, 'red')])),
                ('salt', models.FloatField()),
                ('salt_colour', models.IntegerField(choices=[(0, 'white'), (1, 'green'), (2, 'amber'), (3, 'red')])),
                ('carbs', models.FloatField()),
                ('carbs_colour', models.IntegerField(choices=[(0, 'white'), (1, 'green'), (2, 'amber'), (3, 'red')])),
                ('protein', models.FloatField()),
                ('protein_colour', models.IntegerField(choices=[(0, 'white'), (1, 'green'), (2, 'amber'), (3, 'red')])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_nutrition', to='mealplanner.recipe')),
            ],
        ),
    ]
