# Generated by Django 5.1.2 on 2025-01-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0002_remove_ingredientinrecipe_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipenutrition',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipenutrition',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mealplanner.recipe'),
        ),
    ]
