# Generated by Django 5.1.2 on 2025-01-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0003_remove_recipenutrition_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipenutrition',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='recipenutrition',
            name='salt_colour',
        ),
        migrations.RemoveField(
            model_name='recipenutrition',
            name='saturates',
        ),
        migrations.RemoveField(
            model_name='recipenutrition',
            name='saturates_colour',
        ),
        migrations.RemoveField(
            model_name='recipenutrition',
            name='sugars',
        ),
        migrations.RemoveField(
            model_name='recipenutrition',
            name='sugars_colour',
        ),
    ]
